CREATE TABLE SALARIES(
    ID NUMBER (*,0) NOT NULL, 
    EMPLOYEE_ID NUMBER (*,0), 
    PROJECT_ID NUMBER (*,0), 
    SALARY NUMBER (10,2) NOT NULL,
     CONSTRAINT PK_SALARIES PRIMARY KEY (ID),
     CONSTRAINT SALARIESVALORES CHECK (SALARY>1000));
        
CREATE TABLE PROJECTS(
    ID NUMBER (*,0), 
    CODE VARCHAR2(255 BYTE) NOT NULL, 
    MANAGER_ID NUMBER(*,0), 
    BUDGET NUMBER (10,2) NOT NULL,
    DATE_OF_BEGINNING DATE,
    DATE_OF_ENDINING DATE,
      CONSTRAINT PROJECTS_PK PRIMARY KEY (ID));
      
    
CREATE TABLE EMPLOYEES(
    ID NUMBER (*,0) NOT NULL, 
    MANAGER_ID NUMBER (*,0) NOT NULL, 
    DATE_OF_JOINING DATE NOT NULL, 
    FULL_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT EMPLYEES_PK PRIMARY KEY (ID));
    
ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID);
ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID);
ALTER TABLE PROJECTS ADD CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(MANAGER_ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(MANAGER_ID);

select count employee_id from SALARIES WHERE PROJECT_ID=48205501099;