create TABLE SALARIES(
    ID NUMBER (*,0) NOT NULL, 
    EMPLOYEE_ID NUMBER (*,0), 
    PROJECT_ID NUMBER (*,0), 
    SALARY NUMBER (10,2) NOT NULL,
     CONSTRAINT id_SALARIES PRIMARY KEY (id),
     CONSTRAINT SALARIES CHECK (SALARY>1000),
    FOREIGN KEY (SALARY_EMPLOYEE) REFERENCES PROJECTS(ID),
    FOREIGN KEY (SALARY_PROJECT) REFERENCES EMPLOYEES(ID) 
    );
    
create TABLE PROJECTS(
    ID NUMBER (*,0) NOT NULL, 
    CODE VARCHAR2(255) NOT NULL, 
    MANAGER_ID NUMBER(*,0) NOT NULL, 
    BUDGET NUMBER (10,2) NOT NULL,
    DATE_OF_BEGINNING DATE,
    DATE_OF_ENDINING,
      CONSTRAINT PROJECTS_PK PRIMARY KEY (ID),
      FOREIGN KEY (MANAGER_PROJECT) REFERENCES EMPLOYEES(MANAGER_ID)
    );

create TABLE EMPLOYEES(
    ID NUMBER (*,0) NOT NULL, 
    MANAGER_ID NUMBER (*,0) NOT NULL, 
    DATE_OF_JOINING DATE NOT NULL, 
    FULL_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT EMPLYEES_PK PRIMARY KEY (ID),
    FOREIGN KEY (MANAGER) REFERENCES PROJECTS(MANAGER_ID),
    );

select count employee_id from SALARIES WHERE PROJECT_ID=48205501099;